parameters:
#    gu_bru_je_core.example.class: GuBruJe\CoreBundle\Example

services:
#    gu_bru_je_core.example:
#        class: %gu_bru_je_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


## src/Acme/MainBundle/Resources/config/services.yml
#services:
#    acme_main.menu_builder:
#        class: Acme\MainBundle\Menu\MenuBuilder
#        arguments: ["@knp_menu.factory"]
#
#    acme_main.menu.main:
#        class: Knp\Menu\MenuItem # the service definition requires setting the class
#        factory_service: acme_main.menu_builder
#        factory_method: createMainMenu
#        arguments: ["@request"]
#        scope: request # needed as we have the request as a dependency here
#        tags:
#            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu