annonce:
    path:     /
    defaults: { _controller: "GuBruJeMusicalBundle:Annonce:index" }

annonce_show:
    path:     /{id}/show
    defaults: { _controller: "GuBruJeMusicalBundle:Annonce:show" }

annonce_new:
    path:     /new
    defaults: { _controller: "GuBruJeMusicalBundle:Annonce:new" }

annonce_create:
    path:     /create
    defaults: { _controller: "GuBruJeMusicalBundle:Annonce:create" }
    requirements: { _method: post }

annonce_edit:
    path:     /{id}/edit
    defaults: { _controller: "GuBruJeMusicalBundle:Annonce:edit" }

annonce_update:
    path:     /{id}/update
    defaults: { _controller: "GuBruJeMusicalBundle:Annonce:update" }
    requirements: { _method: post|put }

annonce_delete:
    path:     /{id}/delete
    defaults: { _controller: "GuBruJeMusicalBundle:Annonce:delete" }
    requirements: { _method: post|delete }


annonce_ajouter_commentaire:
    path:     add/{id}/commentaire
    defaults: { _controller: "GuBruJeMusicalBundle:Annonce:ajouterCommentaire" }

annonce_supprimer_commentaire:
    pattern: /supprimer/commentaire/{id}
    defaults: { _controller: "GuBruJeMusicalBundle:Annonce:supprimerCommentaire" }
    requirements:
        id: \d+

annonce_rss:
    pattern: /rss
    defaults: { _controller: "GuBruJeMusicalBundle:Annonce:feed" }
