<?php

namespace GuBruJe\MusicalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends EntityRepository
{

    public function findValideAnnonces($nbr = null)
    {
        $qb = $this->createQueryBuilder('a')
            ->join('a.statut', 's')
            ->where('s.nom = :statut')
            ->setParameter('statut', 'Valide')
            ->orderBy('a.date', 'desc');
        if($nbr !== null){
            $qb->setMaxResults($nbr);
        }

        return $qb->getQuery()->getResult();
    }


}
