<?php

namespace GuBruJe\MusicalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeInformationRepository extends EntityRepository
{
}
